### ISSUE TITLE
Passed Command

### ISSUE THREAD

**Issue by chopo156** [lilabyte/fivem-deXFuscator#1]
Thanks for this piece of art, but keep saying "you didn´t passed any command! even with the "help"

**Comment by lilabyte** [comment]
Can you provide me any screenshots or video?

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket

**Comment by chopo156** [comment]
Sorry lil, i fixed it, isted of command i just passed the name of the file inside the app.js, but i found that some script give me some weird erros but i post in other issue ticket
