### ISSUE TITLE
bug with any xfuscator 

### ISSUE THREAD

**Issue by chopo156** [lilabyte/fivem-deXFuscator#2]
![Untitled](https://user-images.githubusercontent.com/5839632/93945209-51e99c80-fceb-11ea-866b-08f271099bed.png)
Hi!, i have this bug with all of script i tested, i didnt see any problems with the script you share with the resource.

**Comment by lilabyte** [comment]
Can you link up one of this files? I will check it

**Comment by chopo156** [comment]
[main.zip](https://github.com/lilabyte/fivem-deXFuscator/files/5268070/main.zip)
https://www.virustotal.com/gui/file/5c50e7c41db7a9be482be165e28dd92c6b0b9d997189478225dbad1106e91059/details
 Sorry i have uploaded as a zip because github

**Comment by lilabyte** [comment]
Ok, I'll add this obfuscation method to my deobfuscator when I'll find a while.

**Comment by chopo156** [comment]
Thanks lil!
