### ISSUE TITLE
bug UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Diggeris** [lilabyte/fivem-deXFuscator#3]
![image](https://user-images.githubusercontent.com/47028701/118710318-cc40d100-b826-11eb-920a-57438fcbdfff.png)

I can't add you in Discord.

**Comment by lilabyte** [comment]
Hi, this deXFuscator was made for old versions of xFuscator and your file is probably using the newer version or slightly modified version. I'm working on new deobfuscation tool for all xFuscator versions and more obfuscation methods like PSU or Ironbrew. If you need to add me on discord use this account: lilabyte#0793 or any other medium that is assigned to my [twitch.tv/lilabyte](https://twitch.tv/lilabyte) profile. I will leave this issue closed and will re-open it when the new deobfuscation tool will be available so you can get notified about it.
